name: Convert Modified Files to PDF

on:
  push:
    paths:
      - '**/*.ipynb'
      - '**/*.pptx'

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install nbconvert
          sudo apt-get update
          sudo apt-get install -y texlive-xetex pandoc libreoffice

      - name: Get modified notebooks and presentations
        id: get_files
        run: |
          git fetch origin main
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} > changed_files.txt

          # Ensure these files exist even if grep finds nothing
          grep '.ipynb$' changed_files.txt > changed_ipynb.txt || touch changed_ipynb.txt
          grep '.pptx$' changed_files.txt > changed_pptx.txt || touch changed_pptx.txt

          echo "Changed notebooks:"
          cat changed_ipynb.txt

          echo "Changed presentations:"
          cat changed_pptx.txt

      - name: Convert notebooks to PDF
        run: |
          mkdir -p pdfs
          while IFS= read -r file; do
            [ -f "$file" ] && {
              echo "Converting notebook $file"
              output_dir="pdfs/$(dirname "$file")"
              mkdir -p "$output_dir"
              jupyter nbconvert --to pdf "$file" --output-dir "$output_dir"
            }
          done < changed_ipynb.txt

      - name: Convert PPTX to PDF
        run: |
          mkdir -p pdfs
          while IFS= read -r file; do
            [ -f "$file" ] && {
              echo "Converting presentation $file"
              output_dir="pdfs/$(dirname "$file")"
              mkdir -p "$output_dir"
              libreoffice --headless --convert-to pdf "$file" --outdir "$output_dir"
            }
          done < changed_pptx.txt

      - name: Upload PDFs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: converted-pdfs
          path: pdfs/
